import ROOT

import array
import histmgr
import funcs
import os
import math
from pyplot import histutils
#from ztautau.samples import samples
#from ztautau.plots   import vars
from systematics     import *

#trax = None
trax = "1Track"
#trax = "3Track"

f = ROOT.TFile('./trigger_chain_effiencies.root')

L1_data_stat_1Track= f.Get("L1_data_stat_1Track")
L1_data_sys_1Track= f.Get("L1_data_sys_1Track")
L1_eff_MC_1Track= f.Get("L1_eff_MC_1Track")
L1_eff_data_1Track= f.Get("L1_eff_data_1Track")

L1_data_stat_3Track= f.Get("L1_data_stat_3Track")
L1_data_sys_3Track= f.Get("L1_data_sys_3Track")
L1_eff_MC_3Track= f.Get("L1_eff_MC_3Track")
L1_eff_data_3Track = f.Get("L1_eff_data_3Track")

BDT_1p_MC = f.Get('BDT_mc_1Track')
BDT_1p_data = f.Get('BDT_data_1Track')
Trk_1p_MC = f.Get('tracking_mc_1Track')
Trk_1p_data = f.Get('tracking_data_1Track')
PTcut_1p_MC = f.Get('ptcut_mc_1Track')
PTcut_1p_data = f.Get('ptcut_data_1Track')

BDT_3p_MC = f.Get('BDT_mc_3Track')
BDT_3p_data = f.Get('BDT_data_3Track')
Trk_3p_MC = f.Get('tracking_mc_3Track')
Trk_3p_data = f.Get('tracking_data_3Track')
PTcut_3p_MC = f.Get('ptcut_mc_3Track')
PTcut_3p_data = f.Get('ptcut_data_3Track')

c = ROOT.TCanvas("trig_effs","trig_effs",600,600)
#c.Divide(2,4)
pad1 = ROOT.TPad("pad1","pad1",0.,0.75,0.5,1.)
pad1.SetTicky()
pad1.SetTickx()
pad1.SetLogx()
pad1.SetLeftMargin(0.12)
pad1.Draw()

pad2 = ROOT.TPad("pad2","pad2",0.,0.5,0.5,0.75)
pad2.SetTicky()
pad2.SetTickx()
pad2.SetLogx()
pad2.SetLeftMargin(0.12)
pad2.Draw()

pad3 = ROOT.TPad("pad3","pad3",0.,0.25,0.5,0.5)
pad3.SetTicky()
pad3.SetTickx()
pad3.SetLogx()
pad3.SetLeftMargin(0.12)
pad3.Draw()

pad4 = ROOT.TPad("pad4","pad4",0.,0,0.5,0.25)
pad4.SetTicky()
pad4.SetTickx()
pad4.SetBottomMargin(0.27)
pad4.SetLogx()
pad4.SetLeftMargin(0.12)
pad4.Draw()

pad5 = ROOT.TPad("pad5","pad5",0.5,0.75,1,1.)
pad5.SetTicky()
pad5.SetTickx()
pad5.SetLogx()
pad5.SetLeftMargin(0.12)
pad5.Draw()

pad6 = ROOT.TPad("pad6","pad6",0.5,0.5,1,0.75)
pad6.SetTicky()
pad6.SetTickx()
pad6.SetLogx()
pad6.SetLeftMargin(0.12)
pad6.Draw()

pad7 = ROOT.TPad("pad7","pad7",0.5,0.25,1,0.5)
pad7.SetTicky()
pad7.SetTickx()
pad7.SetLogx()
pad7.SetLeftMargin(0.12)
pad7.Draw()

pad8 = ROOT.TPad("pad8","pad8",0.5,0.,1,0.25)
pad8.SetTicky()
pad8.SetTickx()
pad8.SetBottomMargin(0.25)
pad8.SetLeftMargin(0.12)
pad8.SetLogx()
pad8.Draw()

pad1.cd()
fr1 = pad1.DrawFrame(0,0,300,1,';%s;Data/exp.'%('Offline Tau P_{T} [GeV]'))
eff_L1 = ROOT.TMultiGraph()
eff_L1.Add(L1_data_stat_1Track,"E2")
eff_L1.Add(L1_data_sys_1Track,"E2")
eff_L1.Add(L1_eff_MC_1Track,"APZ")
eff_L1.Add(L1_eff_data_1Track,"APZ")
eff_L1.Draw("a Same")

xaxis_bot1 = eff_L1.GetXaxis()
yaxis_bot1 = eff_L1.GetYaxis()
xaxis_bot1.SetMoreLogLabels()
xaxis_bot1.SetLabelFont(42)
yaxis_bot1.SetLabelFont(42)
xaxis_bot1.SetRangeUser(20,300)
#xaxis_bot1.SetTitle('Offline Tau P_{T} [GeV]')
yaxis_bot1.SetNdivisions(6)
xaxis_bot1.SetNoExponent()
xaxis_bot1.SetNdivisions(510)
xaxis_bot1.SetTitleOffset(1)
yaxis_bot1.SetTitle("Data/exp.")
yaxis_bot1.SetTitleOffset(0.7)
yaxis_bot1.SetLabelSize( 0.088)
xaxis_bot1.SetLabelSize( 0.087)
yaxis_bot1.SetTitleSize( 0.088)
xaxis_bot1.SetTitleSize( 0.1)
pad1.RedrawAxis()
tlatex = ROOT.TLatex()
tlatex.SetNDC()
tlatex.SetTextFont(42)
tlatex.SetTextSize(0.08)
tlatex.DrawLatex(0.6,0.36,'1-prong')


pad2.cd()
fr2 = pad2.DrawFrame(0,0.8,300,1.2,';%s;Data/exp.'%('Offline Tau P_{T} [GeV]'))
tot_ratio_pt_1p = ROOT.TMultiGraph()
tot_ratio_pt_1p.Add(PTcut_1p_MC,"E2")
tot_ratio_pt_1p.Add(PTcut_1p_data,"APZ")
tot_ratio_pt_1p.Draw("a Same")

xaxis_bot2 = tot_ratio_pt_1p.GetXaxis()
yaxis_bot2 = tot_ratio_pt_1p.GetYaxis()
xaxis_bot2.SetMoreLogLabels()
xaxis_bot2.SetLabelFont(42)
yaxis_bot2.SetLabelFont(42)
xaxis_bot2.SetRangeUser(20,300)
#xaxis_bot2.SetTitle('Offline Tau P_{T} [GeV]')
yaxis_bot2.SetNdivisions(6)
xaxis_bot2.SetNoExponent()
xaxis_bot2.SetNdivisions(510)
xaxis_bot2.SetTitleOffset(1)
yaxis_bot2.SetTitle("Pt Cut Eff.")
yaxis_bot2.SetTitleOffset(0.7)
yaxis_bot2.SetLabelSize( 0.088)
xaxis_bot2.SetLabelSize( 0.087)
yaxis_bot2.SetTitleSize( 0.088)
xaxis_bot2.SetTitleSize( 0.1)
pad2.RedrawAxis()

pad3.cd()
fr3 = pad3.DrawFrame(0,0.8,300,1.2,';%s;Data/exp.'%('Offline Tau P_{T} [GeV]'))
tot_ratio_trk_1p = ROOT.TMultiGraph()
tot_ratio_trk_1p.Add(Trk_1p_MC,"E2")
tot_ratio_trk_1p.Add(Trk_1p_data,"APZ")
tot_ratio_trk_1p.Draw("a Same")

xaxis_bot3 = tot_ratio_trk_1p.GetXaxis()
yaxis_bot3 = tot_ratio_trk_1p.GetYaxis()
xaxis_bot3.SetMoreLogLabels()
xaxis_bot3.SetLabelFont(42)
yaxis_bot3.SetLabelFont(42)
xaxis_bot3.SetRangeUser(20,300)
#xaxis_bot3.SetTitle('Offline Tau P_{T} [GeV]')
yaxis_bot3.SetNdivisions(6)
xaxis_bot3.SetNoExponent()
xaxis_bot3.SetNdivisions(510)
xaxis_bot3.SetTitleOffset(1)
yaxis_bot3.SetTitle("Trk. Eff.")
yaxis_bot3.SetTitleOffset(0.7)
yaxis_bot3.SetLabelSize( 0.088)
xaxis_bot3.SetLabelSize( 0.087)
yaxis_bot3.SetTitleSize( 0.088)
xaxis_bot3.SetTitleSize( 0.1)
pad3.RedrawAxis()

pad4.cd()
fr4 = pad4.DrawFrame(0,0.8,300,1.2,';%s;Data/exp.'%('Offline Tau P_{T} [GeV]'))
tot_ratio_bdt_1p = ROOT.TMultiGraph()
tot_ratio_bdt_1p.Add(BDT_1p_MC,"E2")
tot_ratio_bdt_1p.Add(BDT_1p_data,"APZ")
tot_ratio_bdt_1p.Draw("a Same")

xaxis_bot4 = tot_ratio_bdt_1p.GetXaxis()
yaxis_bot4 = tot_ratio_bdt_1p.GetYaxis()
xaxis_bot4.SetMoreLogLabels()
xaxis_bot4.SetLabelFont(42)
yaxis_bot4.SetLabelFont(42)
xaxis_bot4.SetRangeUser(20,300)
xaxis_bot4.SetTitle('Offline Tau P_{T} [GeV]')
yaxis_bot4.SetNdivisions(6)
xaxis_bot4.SetNoExponent()
xaxis_bot4.SetNdivisions(510)
xaxis_bot4.SetTitleOffset(1)
yaxis_bot4.SetTitle("BDT Eff.")
yaxis_bot4.SetTitleOffset(0.7)
yaxis_bot4.SetLabelSize( 0.088)
xaxis_bot4.SetLabelSize( 0.087)
yaxis_bot4.SetTitleSize( 0.088)
xaxis_bot4.SetTitleSize( 0.1)
pad4.RedrawAxis()

pad5.cd()
fr5 = pad5.DrawFrame(0,0,300,1,';%s;Data/exp.'%('Offline Tau P_{T} [GeV]'))
eff_L1_3p = ROOT.TMultiGraph()
eff_L1_3p.Add(L1_data_stat_3Track,"E2")
eff_L1_3p.Add(L1_data_sys_3Track,"E2")
eff_L1_3p.Add(L1_eff_MC_3Track,"APZ")
eff_L1_3p.Add(L1_eff_data_3Track,"APZ")
eff_L1_3p.Draw("a Same")

xaxis_bot5 = eff_L1_3p.GetXaxis()
yaxis_bot5 = eff_L1_3p.GetYaxis()
xaxis_bot5.SetMoreLogLabels()
xaxis_bot5.SetLabelFont(42)
yaxis_bot5.SetLabelFont(42)
xaxis_bot5.SetRangeUser(20,300)
#xaxis_bot5.SetTitle('Offline Tau P_{T} [GeV]')
yaxis_bot5.SetNdivisions(6)
xaxis_bot5.SetNoExponent()
xaxis_bot5.SetNdivisions(510)
xaxis_bot5.SetTitleOffset(1)
yaxis_bot5.SetTitle("Data/exp.")
yaxis_bot5.SetTitleOffset(0.55)
yaxis_bot5.SetLabelSize( 0.088)
xaxis_bot5.SetLabelSize( 0.087)
yaxis_bot5.SetTitleSize( 0.088)
xaxis_bot5.SetTitleSize( 0.1)
pad5.RedrawAxis()
tlatex = ROOT.TLatex()
tlatex.SetNDC()
tlatex.SetTextFont(42)
tlatex.SetTextSize(0.08)
tlatex.DrawLatex(0.6,0.36,'3-prong')

pad6.cd()
fr6 = pad6.DrawFrame(0,0.8,300,1.2,';%s;Data/exp.'%('Offline Tau P_{T} [GeV]'))
tot_ratio_pt_3p = ROOT.TMultiGraph()
tot_ratio_pt_3p.Add(PTcut_3p_MC,"E2")
tot_ratio_pt_3p.Add(PTcut_3p_data,"APZ")
tot_ratio_pt_3p.Draw("a Same")

xaxis_bot6 = tot_ratio_pt_3p.GetXaxis()
yaxis_bot6 = tot_ratio_pt_3p.GetYaxis()
xaxis_bot6.SetMoreLogLabels()
xaxis_bot6.SetLabelFont(42)
yaxis_bot6.SetLabelFont(42)
xaxis_bot6.SetRangeUser(20,300)
#xaxis_bot6.SetTitle('Offline Tau P_{T} [GeV]')
yaxis_bot6.SetNdivisions(6)
xaxis_bot6.SetNoExponent()
xaxis_bot6.SetNdivisions(510)
xaxis_bot6.SetTitleOffset(1)
yaxis_bot6.SetTitle("Pt Cut Eff.")
yaxis_bot6.SetTitleOffset(0.55)
yaxis_bot6.SetLabelSize( 0.088)
xaxis_bot6.SetLabelSize( 0.087)
yaxis_bot6.SetTitleSize( 0.088)
xaxis_bot6.SetTitleSize( 0.1)
pad6.RedrawAxis()

pad7.cd()
fr7 = pad7.DrawFrame(0,0.8,300,1.2,';%s;Data/exp.'%('Offline Tau P_{T} [GeV]'))
tot_ratio_trk_3p = ROOT.TMultiGraph()
tot_ratio_trk_3p.Add(Trk_3p_MC,"E2")
tot_ratio_trk_3p.Add(Trk_3p_data,"APZ")
tot_ratio_trk_3p.Draw("a Same")

xaxis_bot7 = tot_ratio_trk_3p.GetXaxis()
yaxis_bot7 = tot_ratio_trk_3p.GetYaxis()
xaxis_bot7.SetMoreLogLabels()
xaxis_bot7.SetLabelFont(42)
yaxis_bot7.SetLabelFont(42)
xaxis_bot7.SetRangeUser(20,300)
#xaxis_bot7.SetTitle('Offline Tau P_{T} [GeV]')
yaxis_bot7.SetNdivisions(6)
xaxis_bot7.SetNoExponent()
xaxis_bot7.SetNdivisions(510)
xaxis_bot7.SetTitleOffset(1)
yaxis_bot7.SetTitle("Trk. Eff.")
yaxis_bot7.SetTitleOffset(0.55)
yaxis_bot7.SetLabelSize( 0.088)
xaxis_bot7.SetLabelSize( 0.087)
yaxis_bot7.SetTitleSize( 0.088)
xaxis_bot7.SetTitleSize( 0.1)
pad7.RedrawAxis()

pad8.cd()
fr8 = pad8.DrawFrame(0,0.8,300,1.2,';%s;Data/exp.'%('Offline Tau P_{T} [GeV]'))
tot_ratio_bdt_3p = ROOT.TMultiGraph()
tot_ratio_bdt_3p.Add(BDT_3p_MC,"E2")
tot_ratio_bdt_3p.Add(BDT_3p_data,"APZ")
tot_ratio_bdt_3p.Draw("a Same")

xaxis_bot8 = tot_ratio_bdt_3p.GetXaxis()
yaxis_bot8 = tot_ratio_bdt_3p.GetYaxis()
xaxis_bot8.SetMoreLogLabels()
xaxis_bot8.SetLabelFont(42)
yaxis_bot8.SetLabelFont(42)
xaxis_bot8.SetRangeUser(20,300)
xaxis_bot8.SetTitle('Offline Tau P_{T} [GeV]')
yaxis_bot8.SetNdivisions(6)
xaxis_bot8.SetNoExponent()
xaxis_bot8.SetNdivisions(510)
xaxis_bot8.SetTitleOffset(1)
yaxis_bot8.SetTitle("BDT Eff.")
yaxis_bot8.SetTitleOffset(0.55)
yaxis_bot8.SetLabelSize( 0.088)
xaxis_bot8.SetLabelSize( 0.087)
yaxis_bot8.SetTitleSize( 0.088)
xaxis_bot8.SetTitleSize( 0.1)
pad8.RedrawAxis()

g = ROOT.TFile('./multipadeffs.root', 'recreate')
c.Write()
g.Close()
c.Draw()
